name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t backend-test ./backend

      - name: Build frontend image
        run: docker build -t frontend-test ./frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-leela216


        with:
          username: ${{ secrets.DOCKERHUB_K.Leela Krishna  }}
          password: ${{ secrets.DOCKERHUB_Leela@2002 }}

      - name: Build & Push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_K.Leela Krishna  }}/capstone-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_K.Leela Krishna }}/capstone-backend:latest

      - name: Build & Push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_K.Leela Krishna }}/capstone-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_K.Leela Krishna }}/capstone-frontend:latest
