name: CI-CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build -t backend-test ./backend

      - name: Build frontend image
        run: docker build -t frontend-test ./frontend

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.leela216 }}
          password: ${{ secrets.github-actions }}

      - name: Push backend image
        run: |
          docker build -t leela216/capstone-backend:latest ./backend
          docker push leela216/capstone-backend:latest

      - name: Push frontend image
        run: |
          docker build -t leela216/capstone-frontend:latest ./frontend
          docker push leela216/capstone-frontend:latest
